src/Entity/CircuitsTouristiques.php
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use Gedmo\Mapping\Annotation as Gedmo;
use PhpParser\Node\Expr\Cast\Double;
use Symfony\Component\Serializer\Annotation\Groups;
use ApiPlatform\Core\Annotation\ApiSubresource;
use App\Repository\CircuitsTouristiquesRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;


/**
 * @ORM\Entity(repositoryClass=CircuitsTouristiquesRepository::class)
 * @ApiResource( normalizationContext={"groups"={"circuit:read"}})
 */
class CircuitsTouristiques
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     *  @Groups({"lieux:read","ville:read","circuit:read","catcircuit:read"})
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Groups({"lieux:read","ville:read","circuit:read","catcircuit:read"})
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Groups({"lieux:read","ville:read","circuit:read","catcircuit:read"})
     */
    private $video;

    /**
     * @ORM\Column(type="text", length=255, nullable=true)
     * @Groups({"lieux:read","ville:read","circuit:read","catcircuit:read"})
     */
    private $Description;

    /**
     * @ORM\Column(type="text", length=255, nullable=true)
     * @Groups({"lieux:read","ville:read","circuit:read","catcircuit:read"})
     */
    private $CourteDescription;

    /**
     * @ORM\Column(type="float", nullable=true)
     * @Groups({"lieux:read","ville:read","circuit:read","catcircuit:read"})
     */
    private $Prix;

    /**
     * @ORM\Column(type="float", nullable=true)
     * @Groups({"lieux:read","ville:read","circuit:read","catcircuit:read"})
     */
    private $Distance;

    /**
     * @ORM\Column(type="integer", nullable=true)
     * @Groups({"lieux:read","ville:read","circuit:read","catcircuit:read"})
     */
    private $Duree;

    /**
     * @ORM\OneToMany(targetEntity=PointsArrets::class, mappedBy="circuits")
     * @Groups({"lieux:read","ville:read","circuit:read","catcircuit:read","pointarret:read"})
     */
    private $pointsArrets;

    /**
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="datetime")
     * @Gedmo\Timestampable(on="update")
     */
    private $updatedAt;

    /**
     * @ORM\OneToMany(targetEntity=ImagesCircuits::class, mappedBy="circuit")
     *  @Groups({"circuit:read","catcircuit:read"})
     */
    private $images;

    /**
     * @ORM\OneToMany(targetEntity=CommentairesCircuits::class, mappedBy="circuit")
     *  @Groups({"circuit:read"})
     */
    private $commentaires;

    /**
     * @ORM\OneToMany(targetEntity=Reservations::class, mappedBy="circuit")
     */
    private $reservations;

    /**
     * @ORM\ManyToOne(targetEntity=CategoriesCircuit::class, inversedBy="circuit")
     *  
     *  
     */
    private $categorie;

    public function __construct()
    {
        $this->pointsArrets = new ArrayCollection();
        $this->images = new ArrayCollection();
        $this->commentaires = new ArrayCollection();
        $this->reservations = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getVideo(): ?string
    {
        return $this->video;
    }

    public function setVideo(?string $video): self
    {
        $this->video = $video;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(?string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getCourteDescriptionn(): ?string
    {
        return $this->CourteDescription;
    }

    public function setCourteDescription(?string $CourteDescription): self
    {
        $this->CourteDescription = $CourteDescription;

        return $this;
    }

    public function getPrix(): ?float
    {
        return $this->Prix;
    }

    public function setPrix(?float $Prix): self
    {
        $this->Prix = $Prix;

        return $this;
    }

    public function getDistance(): ?float
    {
        return $this->Distance;
    }

    public function setDistance(?float $Distance): self
    {
        $this->Distance = $Distance;

        return $this;
    }

    public function getDuree(): ?int
    {
        return $this->Duree;
    }

    public function setDuree(?int $Duree): self
    {
        $this->Duree = $Duree;

        return $this;
    }

    /**
     * @return Collection|PointsArrets[]
     */
    public function getPointsArrets(): Collection
    {
        return $this->pointsArrets;
    }

    public function addPointsArret(PointsArrets $pointsArret): self
    {
        if (!$this->pointsArrets->contains($pointsArret)) {
            $this->pointsArrets[] = $pointsArret;
            $pointsArret->setCircuits($this);
        }

        return $this;
    }

    public function removePointsArret(PointsArrets $pointsArret): self
    {
        if ($this->pointsArrets->removeElement($pointsArret)) {
            // set the owning side to null (unless already changed)
            if ($pointsArret->getCircuits() === $this) {
                $pointsArret->setCircuits(null);
            }
        }

        return $this;
    }

    public function getCreatedAt(): ?\DateTime
    {
        return $this->createdAt;
    }

    public function setCreatedAt(?\DateTime $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTime
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?\DateTime $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    /**
     * @return Collection<int, ImagesCircuits>
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(ImagesCircuits $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images[] = $image;
            $image->setCircuit($this);
        }

        return $this;
    }

    public function removeImage(ImagesCircuits $image): self
    {
        if ($this->images->removeElement($image)) {
            // set the owning side to null (unless already changed)
            if ($image->getCircuit() === $this) {
                $image->setCircuit(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, CommentairesCircuits>
     */
    public function getCommentaires(): Collection
    {
        return $this->commentaires;
    }

    public function addCommentaire(CommentairesCircuits $commentaire): self
    {
        if (!$this->commentaires->contains($commentaire)) {
            $this->commentaires[] = $commentaire;
            $commentaire->setCircuit($this);
        }

        return $this;
    }

    public function removeCommentaire(CommentairesCircuits $commentaire): self
    {
        if ($this->commentaires->removeElement($commentaire)) {
            // set the owning side to null (unless already changed)
            if ($commentaire->getCircuit() === $this) {
                $commentaire->setCircuit(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Reservations>
     */
    public function getReservations(): Collection
    {
        return $this->reservations;
    }

    public function addReservation(Reservations $reservation): self
    {
        if (!$this->reservations->contains($reservation)) {
            $this->reservations[] = $reservation;
            $reservation->setCircuit($this);
        }

        return $this;
    }

    public function removeReservation(Reservations $reservation): self
    {
        if ($this->reservations->removeElement($reservation)) {
            // set the owning side to null (unless already changed)
            if ($reservation->getCircuit() === $this) {
                $reservation->setCircuit(null);
            }
        }

        return $this;
    }

    public function getCategorie(): ?CategoriesCircuit
    {
        return $this->categorie;
    }

    public function setCategorie(?CategoriesCircuit $categorie): self
    {
        $this->categorie = $categorie;

        return $this;
    }
}

src/Controller/Admin/LieuxInteretsController.php
<?php

namespace App\Controller\Admin;

use App\Entity\CategorieLieuxInterets;
use App\Form\CategorieLieuxInteretsType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Repository\CategorieLieuxInteretsRepository;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

/**
 * @Route("/dashboard/lieux-interets/categories")
 */
class LieuxInteretsController extends AbstractController
{
    /**
     * @Route("/", name="admin_cat_lieux_interets_index", methods={"GET", "POST"})
     */
    public function index(Request $request, CategorieLieuxInteretsRepository $categorieLieuxInteretsRepository): Response
    {
        $categorieLieuxInteret = new CategorieLieuxInterets();
        $form = $this->createForm(CategorieLieuxInteretsType::class, $categorieLieuxInteret);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($categorieLieuxInteret);
            $entityManager->flush();

            return $this->redirectToRoute('admin_cat_lieux_interets_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('admin/lieux_interets/categorie/index.html.twig', [
            'categorie_lieux_interets' => $categorieLieuxInteretsRepository->findBy(["status"=>true]),
            'form' => $form->createView(),
        ]);
    }

     /**
     * @Route("/desactive/{id}", name="admin_cat_lieux_interets_desactive", methods={"GET","POST"})
     */
    public function desactive(CategorieLieuxInterets $categorieLieuxInteret) {
        $entityManager = $this->getDoctrine()->getManager();
        if($categorieLieuxInteret->getStatus() == false) {
            $categorieLieuxInteret->setStatus(true);
          
            $entityManager->persist($categorieLieuxInteret);
            $entityManager->flush();
            $this->addFlash('success', 'La categorie a été activée avec success');
            return $this->json([
                'code'=>200,
                'status'=>$categorieLieuxInteret->getStatus(),
                'message'=>'La propriete est mis en avant'
            ]);
        }
        else {
            $categorieLieuxInteret->setStatus(false);
          
            $entityManager->persist($categorieLieuxInteret);
            $entityManager->flush();
            $this->addFlash('success', 'La catégorie a été supprimée avec success');
            return $this->json([
                'code'=>200,
                'status'=>$categorieLieuxInteret->getStatus(),
                'message'=>'La propriete n\' est plus en avant'
            ]);
        }
    }

    /**
     * @Route("/new", name="admin_cat_lieux_interets_new", methods={"GET", "POST"})
     */
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $categorieLieuxInteret = new CategorieLieuxInterets();
        $form = $this->createForm(CategorieLieuxInteretsType::class, $categorieLieuxInteret);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($categorieLieuxInteret);
            $entityManager->flush();

            return $this->redirectToRoute('admin_cat_lieux_interets_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('admin/lieux_interets/categorie/new.html.twig', [
            'categorie_lieux_interet' => $categorieLieuxInteret,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="admin_cat_lieux_interets_show", methods={"GET"})
     */
    public function show(CategorieLieuxInterets $categorieLieuxInteret): Response
    {
        return $this->render('admin/lieux_interets/categorie/show.html.twig', [
            'categorie_lieux_interet' => $categorieLieuxInteret,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="admin_cat_lieux_interets_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, CategorieLieuxInterets $categorieLieuxInteret, EntityManagerInterface $entityManager): Response
    {
         // $form = $this->createForm(RestaurantsType::class, $restaurant);

         $form = $this->createForm(CategorieLieuxInteretsType::class, $categorieLieuxInteret);
       

         if ($this->handleEditForm($request,$categorieLieuxInteret ,$form)) {
             if ($request->isXmlHttpRequest()) {
                 return new JsonResponse(array(
                     'success' => true,
                 ));
             } else {
 //                return $this->redirectToRoute('app_autoecole_show', array('id' => $autoEcole->getId()));
                 return $this->redirectToRoute('admin_categories_index');
             }
         }
 
         if ($request->isXmlHttpRequest()) {
             return new JsonResponse([
                 'success' => false,
                 'errors' => $form->getErrors(true),
 
             ]);
         }
         else {
             return $this->render('admin/lieux_interets/categorie/edit.html.twig', [
                 'categorieLieuxInteret' => $categorieLieuxInteret,
                 'form' => $form->createView(),
             ]);
         }


     /*   $form = $this->createForm(CategorieLieuxInteretsType::class, $categorieLieuxInteret);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('admin_cat_lieux_interets_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('admin/lieux_interets/categorie/edit.html.twig', [
            'categorie_lieux_interet' => $categorieLieuxInteret,
            'form' => $form,
        ]);*/
    }

    /**
     * @Route("/{id}", name="admin_cat_lieux_interets_delete", methods={"POST"})
     */
    public function delete(Request $request, CategorieLieuxInterets $categorieLieuxInteret, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$categorieLieuxInteret->getId(), $request->request->get('_token'))) {
            $entityManager->remove($categorieLieuxInteret);
            $entityManager->flush();
        }

        return $this->redirectToRoute('admin_cat_lieux_interets_index', [], Response::HTTP_SEE_OTHER);
    }




    public function handleEditForm(Request $request, $categorieLieuxInteret, $form)
    {


        $form->handleRequest($request);



        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();

            //$entity = $form->getData();

            $em->persist($categorieLieuxInteret);
            $em->flush();

            return true;
        }

        return false;
    }

    /**
     * @Route("/{id}/create-form", name="bonsplans_edit",options={"expose"=true})
     */
    public function ajaxEditFormAction(Request $request, CategorieLieuxInterets $categorieLieuxInteret)
    {
        $editForm = $this->createForm(CategorieLieuxInteretsType::class, $categorieLieuxInteret);

        return $this->render('admin/lieux_interets/categorie/edit.html.twig', array(
            'bonsplans' => $categorieLieuxInteret,
            'isModal' => true,
            'single' => true,
            'form' => $editForm->createView(),
        ));
    }
}

templates/lieux_interets/_delete_form.html.twig
<form method="post" action="{{ path('app_lieux_interets_delete', {'id': lieux_interet.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ lieux_interet.id) }}">
    <button class="btn">Delete</button>
</form>

templates/lieux_interets/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/lieux_interets/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit LieuxInterets{% endblock %}

{% block body %}
    <h1>Edit LieuxInterets</h1>

    {{ include('lieux_interets/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_lieux_interets_index') }}">back to list</a>

    {{ include('lieux_interets/_delete_form.html.twig') }}
{% endblock %}

templates/lieux_interets/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}LieuxInterets index{% endblock %}

{% block body %}
    <h1>LieuxInterets index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Description</th>
                <th>Video</th>
                <th>Latitude</th>
                <th>Longitude</th>
                <th>Status</th>
                <th>CreatedAt</th>
                <th>UpdatedAt</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for lieux_interet in lieux_interets %}
            <tr>
                <td>{{ lieux_interet.id }}</td>
                <td>{{ lieux_interet.name }}</td>
                <td>{{ lieux_interet.description }}</td>
                <td>{{ lieux_interet.video }}</td>
                <td>{{ lieux_interet.latitude }}</td>
                <td>{{ lieux_interet.longitude }}</td>
                <td>{{ lieux_interet.status ? 'Yes' : 'No' }}</td>
                <td>{{ lieux_interet.createdAt ? lieux_interet.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ lieux_interet.updatedAt ? lieux_interet.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('app_lieux_interets_show', {'id': lieux_interet.id}) }}">show</a>
                    <a href="{{ path('app_lieux_interets_edit', {'id': lieux_interet.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="10">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_lieux_interets_new') }}">Create new</a>
{% endblock %}

templates/lieux_interets/new.html.twig
{% extends 'admin/admin_base.html.twig' %}

{% block title %}New LieuxInterets{% endblock %}

{% block body %}

  <div class="container-xxl flex-grow-1 container-p-y">
    <div class="row">
        <div class="col-xl">
            <div class="card mb-4">
                <div class="card-header d-flex justify-content-between align-items-center">
                    <h5 class="mb-0">Ajouter une nouveau Lieu d'interet</h5>
                </div>
                <div class="card-body">
                   {{ include('lieux_interets/_form.html.twig') }}
                </div>
            </div>
        </div>


{#       <a href="{{ path('app_lieux_interets_index') }}">back to list</a>#}
    </div>
</div>
     

    
{% endblock %}

templates/lieux_interets/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}LieuxInterets{% endblock %}

{% block body %}
    <h1>LieuxInterets</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ lieux_interet.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ lieux_interet.name }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ lieux_interet.description }}</td>
            </tr>
            <tr>
                <th>Video</th>
                <td>{{ lieux_interet.video }}</td>
            </tr>
            <tr>
                <th>Latitude</th>
                <td>{{ lieux_interet.latitude }}</td>
            </tr>
            <tr>
                <th>Longitude</th>
                <td>{{ lieux_interet.longitude }}</td>
            </tr>
            <tr>
                <th>Status</th>
                <td>{{ lieux_interet.status ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>CreatedAt</th>
                <td>{{ lieux_interet.createdAt ? lieux_interet.createdAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>UpdatedAt</th>
                <td>{{ lieux_interet.updatedAt ? lieux_interet.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_lieux_interets_index') }}">back to list</a>

    <a href="{{ path('app_lieux_interets_edit', {'id': lieux_interet.id}) }}">edit</a>

    {{ include('lieux_interets/_delete_form.html.twig') }}
{% endblock %}